src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     */
    private $User;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $Date;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Total;

    /**
     * @ORM\OneToMany(targetEntity=OrderDetail::class, mappedBy="Ord")
     */
    private $orderDetails;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->Total;
    }

    public function setTotal(int $Total): self
    {
        $this->Total = $Total;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetail $orderDetail): self
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails[] = $orderDetail;
            $orderDetail->setOrd($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): self
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getOrd() === $this) {
                $orderDetail->setOrd(null);
            }
        }

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="integer")
     */
    private $Price;

    /**
     * @ORM\Column(type="float")
     */
    private $Weight;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->Category;
    }

    public function setCategory(string $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(int $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->Weight;
    }

    public function setWeight(float $Weight): self
    {
        $this->Weight = $Weight;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Name')
            ->add('Category')
            ->add('Description')
            ->add('Price')
            ->add('Weight')

            ->add('Image', FileType::class, [
                'label' => 'Product Pic (JGP file)',
                'mapped' => false,
                'required' => false,
            ]);
    }


    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Entity\OrderDetail;
use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\OrderDetailRepository;
use App\Repository\OrderRepository;
use App\Repository\ProductRepository;
use Doctrine\Common\Collections\Criteria;

use Doctrine\DBAL\Exception;
use Doctrine\Persistence\ManagerRegistry;
use Psr\Log\LoggerInterface;
use Swift_Mailer;
use Swift_Message;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/product")
 */
class ProductController extends AbstractController
{


//    public function index(ProductRepository $productRepository, Request $request, int $pageId = 1): Response
//    {
//        $selectedCategory = $request->query->get('category');
//        $minPrice = $request->query->get('minPrice');
//        $maxPrice = $request->query->get('maxPrice');
//
//
//        $expressionBuilder = Criteria::expr();
//        $criteria = new Criteria();
//        if (is_null($minPrice) || empty($minPrice)) {
//            $minPrice = 0;
//        }
//        $criteria->where($expressionBuilder->gte('Price', $minPrice));
//        if (!is_null($maxPrice) && !empty(($maxPrice))) {
//            $criteria->andWhere($expressionBuilder->lte('Price', $maxPrice));
//        }
//        if (!is_null($selectedCategory)) {
//            $criteria->andWhere($expressionBuilder->eq('Category', $selectedCategory));
//        }
//        $filteredList = $productRepository->matching($criteria);
//        $numOfItems = $filteredList->count();   // total number of items satisfied above query
//        $itemsPerPage = 8; // number of items shown each page
//        $filteredList = $filteredList->slice($itemsPerPage * ($pageId - 1), $itemsPerPage);
//        return $this->renderForm('product/index.html.twig', [
//            'products' => $filteredList,
//            'selectedCat' => $selectedCategory ?: 'Cat',
//            'numOfPages' => ceil($numOfItems / $itemsPerPage)
//        ]);
//    }

    /**
     * @Route("/addCart/{id}", name="app_add_cart", methods={"GET"})
     */
    public function addCart(Product $product, Request $request): Response
    {
        $session = $request->getSession();
        $quantity = (int)$request->query->get('quantity');

        //check if cart is empty
        if (!$session->has('cartElements')) {
            //if it is empty, create an array of pairs (prod Id & quantity) to store first cart element.
            $cartElements = array($product->getId() => $quantity * ($quantity + 1));
            //save the array to the session for the first time.
            $session->set('cartElements', $cartElements);
        } else {
            $cartElements = $session->get('cartElements');
            //Add new product after the first time. (would UPDATE new quantity for added product)
            $cartElements = array($product->getId() => $quantity * ($quantity + 1)) + $cartElements;
            //Re-save cart Elements back to session again (after update/append new product to shopping cart)
            $session->set('cartElements', $cartElements);
        }
        return $this->redirectToRoute('app_product_index'); //means 200, successful
    }
    /**
     * @Route("/sendmail", name="app_user_sendmail", methods={"GET"})
     */
    public function sendmail(Swift_Mailer $mailer): Response
    {
        $message = (new Swift_Message('Hello Email'))
            ->setFrom('ldd392002@gmail.com')
            ->setTo('duyle392002@gmail.com')
            ->setBody("3rd Test send email");

        $mailer->send($message);
        return new Response("Send mail successfully");
    }

    /**
     * @Route("/reviewCart", name="app_review_cart", methods={"GET"})
     */
    public function reviewCart(Request $request): Response
    {
        $session = $request->getSession();
        if ($session->has('cartElements')) {
            $cartElements = $session->get('cartElements');
        } else
            $cartElements = [];
        return $this->json($cartElements);
    }


    /**
     * @Route("/checkoutCart", name="app_checkout_cart", methods={"GET"})
     */
    public function checkoutCart(Request               $request,
                                 OrderDetailRepository $orderDetailRepository,
                                 OrderRepository       $orderRepository,
                                 ProductRepository     $productRepository,
                                 ManagerRegistry       $mr): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $entityManager = $mr->getManager();
        $session = $request->getSession(); //get a session
        // check if session has elements in cart
        if ($session->has('cartElements') && !empty($session->get('cartElements'))) {
            try {
                // start transaction!
                $entityManager->getConnection()->beginTransaction();
                $cartElements = $session->get('cartElements');

                //Create new Order and fill info for it. (Skip Total temporarily for now)
                $order = new Order();
                date_default_timezone_set('Asia/Ho_Chi_Minh');
                $order->setDate(new \DateTime());
                /** @var \App\Entity\User $user */
                $user = $this->getUser();
                $order->setUser($user);
                $orderRepository->add($order, true); //flush here first to have ID in Order in DB.

                //Create all Order Details for the above Order
                $total = 0;
                foreach ($cartElements as $product_id => $quantity) {
                    $product = $productRepository->find($product_id);
                    //create each Order Detail
                    $orderDetail = new OrderDetail();
                    $orderDetail->setOrd($order);
                    $orderDetail->setProduct($product);
                    $orderDetail->setQuantity($quantity);
                    $orderDetailRepository->add($orderDetail);

                    $total += $product->getPrice() * $quantity;
                }
                $order->setTotal($total);
                $orderRepository->add($order);
                // flush all new changes (all order details and update order's total) to DB
                $entityManager->flush();

                // Commit all changes if all changes are OK
                $entityManager->getConnection()->commit();

                // Clean up/Empty the cart data (in session) after all.
                $session->remove('cartElements');
            } catch (Exception $e) {
                // If any change above got trouble, we roll back (undo) all changes made above!
                $entityManager->getConnection()->rollBack();
            }
            return new Response("Check in DB to see if the checkout process is successful");
        } else
            return new Response("Nothing in cart to checkout!");
    }
    /**
     * @Route("/manage", name="app_product_manage", methods={"GET"})
     */
    public function manage(ProductRepository $productRepository): Response
    {
        return $this->render('product/mangeproduct.html.twig', [
            'products' => $productRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{pageId }", name="app_product_index", methods={"GET"})
     */
    public function index(LoggerInterface $logger, ProductRepository $productRepository, Request $request, $pageId = 1): Response
    {
        $selectedCategory = $request->query->get('category');
        $Name = $request->query->get('name');
        $minPrice = $request->query->get('minPrice');
        $maxPrice = $request->query->get('maxPrice');
        $sortBy = $request->query->get('sort');
        $orderBy = $request->query->get('order');

        $expressionBuilder = Criteria::expr();
        $criteria = new Criteria();
        if (empty($minPrice)) {
            $minPrice = 0;
        }
        $criteria->where($expressionBuilder->gte('Price', $minPrice));
        if (!is_null($maxPrice) && !empty(($maxPrice))) {
            $criteria->andWhere($expressionBuilder->lte('Price', $maxPrice));
        }
        if (!is_null($selectedCategory)) {
            $criteria->andWhere($expressionBuilder->eq('Category', $selectedCategory));
        }
        if (!is_null($Name) && !empty(($Name))) {
            $criteria->andWhere($expressionBuilder->contains('Name', $Name));
//            $criteria->orWhere($expressionBuilder->contains('description', $Name));

        }
        if (!empty($sortBy)) {
            $criteria->orderBy([$sortBy => ($orderBy == 'asc') ? Criteria::ASC : Criteria::DESC]);
        }
        $filteredList = $productRepository->matching($criteria);

        $numOfItems = $filteredList->count();   // total number of items satisfied above query
        $itemsPerPage = 9; // number of items shown each page
        $logger->info($numOfItems);
        $logger->info($pageId);
        $filteredList = $filteredList->slice((int)$itemsPerPage * ((int)$pageId - 1), (int)$itemsPerPage);

        return $this->renderForm('product/index.html.twig', [
            'products' => $filteredList,
            'selectedCat' => $selectedCategory ?: 'Cat',
            'numOfPages' => ceil($numOfItems / $itemsPerPage)
        ]);
    }

    /**
     * @Route("/create/new", name="app_product_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ProductRepository $productRepository): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $productFile = $form->get('Image')->getData();

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('app_product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn">Delete</button>
</form>

templates/product/_form.html.twig
<div class="container-md col-md-4 col-md-offset-4">
    <h1>Edit Product</h1>
    {{ form_start(form,{'attr':{'class':'form-control'}}) }}
    <label for="product_name" class="form-label">Name</label>
    {{ form_widget(form.Name,{'attr':{'class':'form-control rounded-pill'}}) }}
    <label for="product_category" class="form-label">Category</label>
    {{ form_widget(form.Category,{'attr':{'class':'form-control rounded-pill'}}) }}
    <label for="product_description" class="form-label">Description</label>
    {{ form_widget(form.Description,{'attr':{'class':'form-control rounded-pill'}}) }}
    <label for="product_price" class="form-label">Price</label>
    {{ form_widget(form.Price,{'attr':{'class':'form-control rounded-pill'}}) }}
    <label for="product_weight" class="form-label">Weight</label>
    {{ form_widget(form.Weight,{'attr':{'class':'form-control rounded-pill'}}) }}
    <label for="product_image" class="form-label">Image</label>
    {{ form_row(form.Image) }}
    <button class="form-control rounded-pill btn btn-lg btn-primary border-bottom">{{ button_label|default('Save') }}</button>
    <br>
    {{ form_end(form) }}
</div>

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <h1>Edit Product</h1>

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_product_index') }}">back to list</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product index{% endblock %}

{% block body %}
    <div class="container-md">
        <div class="col ">
            <form action={{ path('app_product_index') }} method="get">
                Category:
                <label>
                    <input name="category" type="checkbox" value="Cat"{{ (selectedCat=="cat") ? 'cat' }}> Cat
                </label>
                <label>
                    <input name="category" type="checkbox" value="food"{{ (selectedCat=="Food") ? 'food' }}> Food
                </label>
                <label>
                    <input name="category" type="checkbox" value="Accessory"{{ (selectedCat=="Accessory") ? 'Accessory' }}>Accessory
                </label>
                <label>
                    <input name="category" type="checkbox" value="Medicine"{{ (selectedCat=="Medicine") ? 'Medicine' }}>Medicine
                </label>
{#                <select name="category">#}
{#                    <option value="Medicine" {{ (selectedCat=="Medicine") }}>Medicine</option>#}
{#                    <option value="Cat" {{ (selectedCat=="cat") }}>Medicine</option>#}
{#                </select>#}

                <br>
                Min Price: <input type="number" name="minPrice"><br>
                Max Price: <input type="number" name="maxPrice"><br>
                <input type="submit" name="selectedCat" value="Filter" class="btn btn-primary"> |
                <a href="{{ path('app_product_index') }}"
                   class="btn btn-primary">Reset</a>
            </form>
        </div>
        {% if app.user=="ROLE_ADMIN" %}
            <div class="mx-auto w-4/5 my-8 btn btn-primary"><a href="{{ path('app_product_new') }}" class="text-white">
                    Create new product</a></div>
        {% endif %}
        <div class="row">
            <div class="col">
                <div class="container">
                    <div class="row">
                        <div class="col-6"><h4>Product Listing</h4></div>
                        <div class="col-3 text-end"><p>Price: </p></div>
                        <div class="col-3">
                            <a href="{{ path(app.request.attributes.get('_route'),
                                app.request.query.all|merge({'sort': 'Price', 'order': 'desc'})) }}"
                               class="btn btn-primary btn-sm">High->Low</a>
                            <a href="{{ path(app.request.attributes.get('_route'),
                                app.request.query.all|merge({'sort': 'Price', 'order': 'asc'})) }}"
                               class="btn btn-primary btn-sm">Low->High</a>
                        </div>
                        <div class="row row-cols-1 row-cols-md-3 g-3">
                            {% for product in products %}
                                <div class="col">
                                    <div class="card card-height-10rem btn"><a
                                                class="text-black list-group-item text-decoration-none text-wrap"
                                                href="{{ path('app_product_show', {'id': product.id}) }}">
                                            {#                                            <img class="card-img-top" src="{{ asset('public/images/'~product.Image) }}"> #}

                                            <img class="card-img-top" src="{{ asset('images/'~product.Image) }}">

                                            <div class="card-body h-100 w-100 fs-5 text-wrap"
                                                 style="width: 8rem;,height: 8rem;">
                                                <h5 class="card-title h-100 w-100 fs-5 text-wrap"
                                                    style="width: 8rem;">{{ product.Name }}</h5>
                                                <h6 class="card-subtitle">Category: {{ product.category }}</h6>
                                                <p>Price: {{ product.price }}</p>
                                            </div>
                                            <div class="card">
                                                <a href="{{ path('app_add_cart', {'id': product.id}) }}"
                                                   class="btn btn-primary d-flex flex-wrap justify-content-center">Add</a>
                                                {#                                            <a href="{{ path('app_product_show', {'id': product.id}) }}" #}
                                                {#                                               class="btn btn-primary">Show</a> #}
                                            </div>
                                        </a>
                                    </div>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="row mt-2">
                            <div style="display:flex;text-align:center;justify-content:center">
                                <nav aria-label="Page navigation">
                                    <ul class="pagination">
                                        {% for i in range(1, numOfPages) %}
                                            {% set style = app.request.get('pageId')==i ? "active" : "" %}
                                            <li class="page-item {{ style }}">
                                                <a class="page-link"
                                                   href={{ path(app.request.attributes.get('_route'),
                                                    app.request.query.all|merge({'pageId': i})) }}>{{ i }}
                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/product/mangeproduct.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product Manage{% endblock %}

{% block body %}
    <h1>Product Management</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Weight</th>
            <th>Image</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ product.name }}</td>
                <td>{{ product.description }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.weight }}</td>
                <td>{{ product.image }}</td>
                <td>
                    <a href="{{ path('app_product_show', {'id': product.id}) }}">Show</a>
                    <a href="{{ path('app_product_edit', {'id': product.id}) }}">Edit</a>
                    {{ include('product/_delete_form.html.twig') }}
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_product_new') }}">Create new</a>
{% endblock %}

templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <h1>Create new Product</h1>

    {{ include('product/_form.html.twig') }}

    <a href="{{ path('app_product_index') }}">back to list</a>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
    <h1>Product</h1>
    <div class="d-flex justify-content-center">
        <div class="row">
            <img class="card" src="{{asset('images/'~product.Image) }}" style="width: 30rem;">
            <table class="row">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ product.id }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ product.Name }}</td>
                </tr>
                <tr>
                    <th>Category</th>
                    <td>{{ product.Category }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ product.Description }}</td>
                </tr>
                <tr>
                    <th>Price</th>
                    <td>{{ product.Price }}</td>S
                </tr>
                <tr>
                    <th>Weight</th>
                    <td>{{ product.Weight }}</td>
                </tr>
                {#            <tr>#}
                {#                <th>Image</th>#}
                {#                <td>{{ product.Image }}</td>#}
                {#            </tr>#}
                </tbody>
            </table>
            <ul>
                <a class="btn btn-primary " href="{{ path('app_add_cart', {'id': product.id}) }}">Add Product To Cart</a><br>
            </ul>
            <ul>
                <a class="btn btn-primary" href="{{ path('app_product_index') }}">Back To Main Page</a>
            </ul>
        </div>
    </div>
    {#    {{ include('product/_delete_form.html.twig') }}#}
{% endblock %}